# Generated by Django 4.1.5 on 2023-02-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='material',
            new_name='notebook',
        ),
    ]
