# Generated by Django 4.1.5 on 2023-02-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_rename_material_order_notebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='pen',
        ),
    ]
