# Generated by Django 4.1.5 on 2023-02-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_rename_address_order_pen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pen',
            field=models.BooleanField(),
        ),
    ]
